[package]
name = "arbiter_template"
version = "0.1.0"
edition = "2021"

[dependencies]
arbiter-core = { git = "https://github.com/primitivefinance/arbiter", branch = "feat/simple" }
tokio = { version = "1.11.0", features = ["full"] }
ethers = { git = "https://github.com/primitivefinance/ethers-rs" }
